### ISSUE TITLE
Gallery Vault support

### ISSUE THREAD

**Issue by Arian03dc** [Magpol/decrypt-calculatorPlusApk#2]
Add decrypt for Gallery Vault app
App extension: com.thinkyeah.galleryvault

I have around of 3 gb of files, and I lost my password, the email can't help. Any solution???

**Comment by Magpol** [comment]
The PIN code is stored as a SHA-1 in /data/data/com.thinkyeah.galleryvault/shared_prefs/Kidd.xml ( field name “LockPin” ). Obviously you need a rooted phone to access this file. Hope this helps in retrieving your files!

**Comment by Arian03dc** [comment]
I don't have rooted phone. I will try. Thanks a lot!!!. Isn't there any other solution, like bruteforce?
