### ISSUE TITLE
Please Make one for Calculator Vault by FIshing Net

### ISSUE THREAD

**Issue by MetalDragonBD** [Magpol/decrypt-calculatorPlusApk#3]
Hi, Can you please make one for calculator vault app here: https://play.google.com/store/apps/details?id=com.hld.anzenbokusucal&hl=en&gl=US

As far as I can see it uses MD5 Decryption with key "0123456789abcdef"

**Comment by Magpol** [comment]
https://github.com/Magpol/decryptCalculatorPhotoVault
